name: ci
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: make test

  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        shell: bash
        run: make test

